version: "3.8"
services:
  schedulerService:
    image: dotollia/msa_schedulerservice:0.3
    container_name: schedulerService
    depends_on:
      - kafkaProducer
    networks:
      my_net:
        aliases:
          - schedulerService

  bankAccountGenerator:
    image: dotollia/msa_bankaccountgenerator:0.2
    container_name: bankAccountGenerator
    ports:
      - "8085:8080"
    networks:
      my_net:
        ipv4_address: 10.20.30.10
        aliases:
          - bankAccountGenerator

  kafkaProducer:
    image: dotollia/msa_kafkaproducer:0.3
    container_name: kafkaProducer
    depends_on:
      - kafka
      - bankAccountGenerator
    ports:
      - "8081:8080"
    networks:
      my_net:
        ipv4_address: 10.20.30.11
        aliases:
          - kafkaProducer

  kafkaConsumer:
    image: dotollia/msa_kafkaconsumer:0.3
    container_name: kafkaConsumer
    ports:
      - "8082:8080"
    networks:
      my_net:
        ipv4_address: 10.20.30.12
        aliases:
          - kafkaConsumer

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: "10.20.30.0/24"
